// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nllpxugnekhilifkfjox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sbHB4dWduZWtoaWxpZmtmam94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjY4MzIsImV4cCI6MjA3NDY0MjgzMn0.scWm3krzseQHRWjC9MeFXg8j3QruQeO0Ow_PKJ3-_Fo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});